### ISSUE TITLE
Split package io.matthewnelson.encoding.builders

### ISSUE THREAD

**Issue by craigraw** [05nelsonm/encoding#124]
The package `io.matthewnelson.encoding.builders` is split across 3 jars. When using Java modules, these jars become modules, and this results in a split package which is disallowed by JPMS. This results in errors at runtime for example: `Package io.matthewnelson.encoding.builders in both module encoding.base16.jvm and module encoding.base32.jvm`.

There are two solutions - either package the `encoding-base*-jvm` jars as one jar, or change the package name in each of the jars, for example: `io.matthewnelson.encoding.builders16`, `io.matthewnelson.encoding.builders32`, `io.matthewnelson.encoding.builders64`.

**Comment by 05nelsonm** [comment]
Deprecation cycle did not work, will need to remove the `.builders` packages from `base16`, `base32`, and `base64` modules.

POA:
 - Release `1.2.3` with deprecation notices and a way for library consumers to gracefully update to new methods
 - Release `2.0.0` with API breaking changes (`...encoding.builders` package removed).
 - Add migration notes to the `CHANGELOG` and release notes.
